#!/usr/bin/env python3
"""Verify BRAM init contents against the original numpy_reference weight bins.

BRAM layout is the one generated by weights/bin2hex.py:
  - 16 bytes per 128-bit BRAM word
  - each bram_init.txt line is written as reversed hex for $readmemh
  - mem[word][8*lane +: 8] corresponds to bytes.fromhex(line)[::-1][lane]
  - matrices are stored as 16x16 pre-tiled row-major tiles
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import sys

import numpy as np


S = 16
WORD = 16
DEPTH = 1 << 14

M1 = 0.00036199
M2 = 0.00143881
M3 = 0.01956364
M4 = 1.00000000

CLASSES = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]


@dataclass(frozen=True)
class Section:
    filename: str
    base: int
    rows: int
    cols: int

    @property
    def nbytes(self) -> int:
        return self.rows * self.cols

    @property
    def end(self) -> int:
        return self.base + (self.nbytes // WORD)


SECTIONS = [
    Section("layer1_weights.bin", 0x0000, 128, 768),
    Section("layer2_weights.bin", 0x1800, 128, 128),
    Section("layer3_weights.bin", 0x1C00, 128, 128),
    Section("layer4_weights.bin", 0x2000, 16, 128),
    Section("input_spectrogram.bin", 0x2400, 16, 768),
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def default_bram_path(root: Path) -> Path:
    hdl_bram = root / "hdl_sources" / "finalprj_rps" / "finalprj_rps.srcs" / "bram_init.txt"
    if hdl_bram.exists():
        return hdl_bram
    return root / "numpy_reference" / "weights" / "bram_init.txt"


def read_bram_init(path: Path, reverse_hex_for_readmemh: bool = True) -> bytearray:
    lines = path.read_text().splitlines()
    if len(lines) != DEPTH:
        raise ValueError(f"{path}: expected {DEPTH} lines, got {len(lines)}")

    mem = bytearray(DEPTH * WORD)
    for addr, line in enumerate(lines):
        text = line.strip()
        if len(text) != WORD * 2:
            raise ValueError(f"{path}:{addr + 1}: expected 32 hex chars, got {len(text)}")
        raw = bytes.fromhex(text)
        word_bytes = raw[::-1] if reverse_hex_for_readmemh else raw
        mem[addr * WORD : (addr + 1) * WORD] = word_bytes
    return mem


def pretile(raw: bytes, rows: int, cols: int) -> bytes:
    n_tile_rows = rows // S
    n_tile_cols = cols // S
    words_per_row = cols // S
    out = bytearray(len(raw))

    for tile_row in range(n_tile_rows):
        for tile_col in range(n_tile_cols):
            for intra_row in range(S):
                actual_row = tile_row * S + intra_row
                src = (actual_row * words_per_row + tile_col) * WORD
                dst = ((tile_row * n_tile_cols + tile_col) * S + intra_row) * WORD
                out[dst : dst + WORD] = raw[src : src + WORD]

    return bytes(out)


def untiling(tiled: bytes, rows: int, cols: int) -> bytes:
    n_tile_rows = rows // S
    n_tile_cols = cols // S
    words_per_row = cols // S
    out = bytearray(len(tiled))

    for tile_row in range(n_tile_rows):
        for tile_col in range(n_tile_cols):
            for intra_row in range(S):
                actual_row = tile_row * S + intra_row
                src = ((tile_row * n_tile_cols + tile_col) * S + intra_row) * WORD
                dst = (actual_row * words_per_row + tile_col) * WORD
                out[dst : dst + WORD] = tiled[src : src + WORD]

    return bytes(out)


def context(values: np.ndarray, index: int, radius: int = 8) -> str:
    start = max(0, index - radius)
    end = min(values.size, index + radius + 1)
    return np.array2string(values[start:end], separator=", ")


def first_mismatch(a: np.ndarray, b: np.ndarray) -> int | None:
    mismatch = np.flatnonzero(a != b)
    if mismatch.size == 0:
        return None
    return int(mismatch[0])


def check_section(mem: bytearray, weights_dir: Path, section: Section) -> np.ndarray:
    raw_path = weights_dir / section.filename
    raw = raw_path.read_bytes()
    expected_size = section.nbytes
    if len(raw) != expected_size:
        raise ValueError(f"{raw_path}: expected {expected_size} bytes, got {len(raw)}")

    bram_start = section.base * WORD
    bram_end = bram_start + section.nbytes
    bram_tiled = bytes(mem[bram_start:bram_end])
    expected_tiled = pretile(raw, section.rows, section.cols)

    bram_i8 = np.frombuffer(bram_tiled, dtype=np.int8)
    expected_i8 = np.frombuffer(expected_tiled, dtype=np.int8)
    mismatch = first_mismatch(bram_i8, expected_i8)

    label = f"{section.filename}"
    if mismatch is None:
        print(f"[CHECK] {label} ... PASS")
    else:
        print(f"[CHECK] {label} ... FAIL")
        print(
            f"  first mismatch tiled_byte_index={mismatch} "
            f"bram={int(bram_i8[mismatch])} bin={int(expected_i8[mismatch])}"
        )
        print(f"  bram context: {context(bram_i8, mismatch)}")
        print(f"  bin  context: {context(expected_i8, mismatch)}")
        raise SystemExit(1)

    raw_from_bram = untiling(bram_tiled, section.rows, section.cols)
    raw_from_bram_i8 = np.frombuffer(raw_from_bram, dtype=np.int8).copy()
    raw_i8 = np.frombuffer(raw, dtype=np.int8)
    raw_mismatch = first_mismatch(raw_from_bram_i8, raw_i8)
    if raw_mismatch is not None:
        print(f"[CHECK] {label} inverse tile restore ... FAIL")
        print(
            f"  first mismatch raw_byte_index={raw_mismatch} "
            f"bram={int(raw_from_bram_i8[raw_mismatch])} bin={int(raw_i8[raw_mismatch])}"
        )
        raise SystemExit(1)

    return raw_from_bram_i8.reshape(section.rows, section.cols)


def numpy_inference_from_reconstructed(mats: dict[str, np.ndarray]) -> np.ndarray:
    x = mats["input_spectrogram.bin"]
    w1 = mats["layer1_weights.bin"]
    w2 = mats["layer2_weights.bin"]
    w3 = mats["layer3_weights.bin"]
    w4 = mats["layer4_weights.bin"]

    y1 = np.dot(x.astype(np.int32), w1.T.astype(np.int32))
    y1 = np.maximum(0, y1)
    x2 = np.clip(np.round(y1 * M1), 0, 127).astype(np.int8)

    y2 = np.dot(x2.astype(np.int32), w2.T.astype(np.int32))
    y2 = np.maximum(0, y2)
    x3 = np.clip(np.round(y2 * M2), 0, 127).astype(np.int8)

    y3 = np.dot(x3.astype(np.int32), w3.T.astype(np.int32))
    y3 = np.maximum(0, y3)
    x4 = np.clip(np.round(y3 * M3), 0, 127).astype(np.int8)

    y4 = np.dot(x4.astype(np.int32), w4.T.astype(np.int32))
    y4 = np.maximum(0, y4)
    return np.clip(np.round(y4 * M4), 0, 127).astype(np.int8)


def numpy_reference_from_bins(weights_dir: Path) -> np.ndarray:
    x = np.fromfile(weights_dir / "input_spectrogram.bin", dtype=np.int8).reshape(16, 768)
    w1 = np.fromfile(weights_dir / "layer1_weights.bin", dtype=np.int8).reshape(128, 768)
    w2 = np.fromfile(weights_dir / "layer2_weights.bin", dtype=np.int8).reshape(128, 128)
    w3 = np.fromfile(weights_dir / "layer3_weights.bin", dtype=np.int8).reshape(128, 128)
    w4 = np.fromfile(weights_dir / "layer4_weights.bin", dtype=np.int8).reshape(16, 128)
    return numpy_inference_from_reconstructed(
        {
            "input_spectrogram.bin": x,
            "layer1_weights.bin": w1,
            "layer2_weights.bin": w2,
            "layer3_weights.bin": w3,
            "layer4_weights.bin": w4,
        }
    )


def print_layout() -> None:
    print("BRAM layout inferred from numpy_reference/weights/bin2hex.py:")
    print("  word width       : 128 bits = 16 bytes")
    print("  line hex order   : bytes reversed before $readmemh")
    print("  RTL lane order   : mem[word][8*lane +: 8], lane0 is least-significant byte")
    print("  matrix tiling    : 16x16 tiles, tile-row then tile-col, 16 intra-row words")
    for section in SECTIONS:
        print(
            f"  {section.filename:22s}: base=0x{section.base:04X}, "
            f"end=0x{section.end:04X}, shape=({section.rows},{section.cols})"
        )
    print()


def maybe_report_other_endian(bram_path: Path, weights_dir: Path) -> None:
    try:
        mem_big = read_bram_init(bram_path, reverse_hex_for_readmemh=False)
        section = SECTIONS[0]
        raw = (weights_dir / section.filename).read_bytes()
        expected = np.frombuffer(pretile(raw, section.rows, section.cols), dtype=np.int8)
        start = section.base * WORD
        got = np.frombuffer(bytes(mem_big[start : start + section.nbytes]), dtype=np.int8)
        if first_mismatch(got, expected) is None:
            print("[INFO] Big-endian line interpretation also matched unexpectedly.")
        else:
            print("[INFO] Big-endian line interpretation does not match; reversed readmemh order is correct.")
    except Exception as exc:
        print(f"[INFO] Big-endian sanity check skipped: {exc}")


def main() -> int:
    root = repo_root()
    weights_dir = root / "numpy_reference" / "weights"
    bram_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else default_bram_path(root)

    if not bram_path.exists():
        raise FileNotFoundError(f"Cannot find bram_init.txt at {bram_path}")

    hdl_bram = root / "hdl_sources" / "finalprj_rps" / "finalprj_rps.srcs" / "bram_init.txt"
    weights_bram = weights_dir / "bram_init.txt"

    print(f"Using bram_init.txt: {bram_path}")
    if hdl_bram.exists() and weights_bram.exists():
        same_file = hdl_bram.read_bytes() == weights_bram.read_bytes()
        print(f"[CHECK] HDL bram_init.txt equals numpy_reference/weights/bram_init.txt ... {'PASS' if same_file else 'FAIL'}")
        if not same_file:
            print(f"  HDL     : {hdl_bram}")
            print(f"  weights : {weights_bram}")
    print()

    print_layout()
    mem = read_bram_init(bram_path, reverse_hex_for_readmemh=True)
    maybe_report_other_endian(bram_path, weights_dir)
    print()

    reconstructed: dict[str, np.ndarray] = {}
    for section in SECTIONS:
        reconstructed[section.filename] = check_section(mem, weights_dir, section)

    bram_out = numpy_inference_from_reconstructed(reconstructed)
    ref_out = numpy_reference_from_bins(weights_dir)
    mismatch = first_mismatch(bram_out.reshape(-1), ref_out.reshape(-1))

    print()
    if mismatch is None:
        print("[CHECK] Reconstructed BRAM numpy inference ... PASS")
    else:
        row = mismatch // ref_out.shape[1]
        col = mismatch % ref_out.shape[1]
        print("[CHECK] Reconstructed BRAM numpy inference ... FAIL")
        print(f"  first mismatch row={row} col={col} bram={int(bram_out[row, col])} ref={int(ref_out[row, col])}")
        raise SystemExit(1)

    np.set_printoptions(threshold=np.inf)
    print()
    print("Final output matrix:")
    print(bram_out)

    print()
    print("Final predictions:")
    predictions = np.argmax(bram_out[:, :9], axis=1)
    for index, class_id in enumerate(predictions):
        print(f"Audio Clip {index + 1:02d}: Class ID = {int(class_id)} ({CLASSES[int(class_id)]})")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
